### ISSUE TITLE
Remove assert(l1.isValid() && l2.isValid());

### ISSUE THREAD

**Issue by lexuanquynh** [zxing-cpp/zxing-cpp#855] opened 2024-10-21 15:00 UTC
I use this library in iOS.
But when I read the requence QRCodes, I got the crash by this line in RegressionLine.h:
```C++
assert(l1.isValid() && l2.isValid());
``` 

use in QRDetector.cpp:
```C++
 if (Size(hori) == 2 && Size(verti) == 2) {
		auto guessed = intersect(RegressionLine(hori[0], hori[1]), RegressionLine(verti[0], verti[1]));
		auto found = LocateAlignmentPattern(image, moduleSize, guessed);
		// search again near that intersection and if the search fails, use the intersection
		if (!found) printf("location guessed at %dx%d\n", x, y);
		apP.set(x, y, found ? *found : guessed);
}
```

I have no way to remove assert line for ignore crash.
Could you help me add the DEBUG flag for debug mode, and don't trigger this code in release mode?
<img width="582" alt="Screenshot 2024-10-21 at 22 00 12" src="https://github.com/user-attachments/assets/6aa59067-2334-434f-b7b6-acc3b530a67f">

**Comment by axxel** [comment] 2024-10-22 07:55
Is it possible for you to provide the image data that caused this assertion to fail, so I can debug it locally?

**Comment by axxel** [comment] 2024-11-04 18:08
Closing this for lack of feedback. If you have more information, let me know and I'll reopen the issue.

**Comment by lexuanquynh** [comment] 2024-11-06 11:57
Sorry I missed the announcement. Here are 7 images for 1 strings:

![photo_2024-11-06 18 55 56](https://github.com/user-attachments/assets/1f451ebf-4ca2-418e-a275-79276affc3b7)
![photo_2024-11-06 18 55 58](https://github.com/user-attachments/assets/5e66a5a0-f229-4224-a56d-efe27a9a61db)
![photo_2024-11-06 18 56 00](https://github.com/user-attachments/assets/3c559dac-45da-440e-9d6d-aef640ceb3cf)
![photo_2024-11-06 18 56 02](https://github.com/user-attachments/assets/a88b3c9b-a56b-42f7-a730-b259af9d7403)
![photo_2024-11-06 18 56 04](https://github.com/user-attachments/assets/5b24a3c1-c7f2-406a-9dd9-ba4b692f9ad7)
![photo_2024-11-06 18 56 05](https://github.com/user-attachments/assets/90fa3d3e-5296-42d5-a778-4b7cea122084)
![photo_2024-11-06 18 56 07](https://github.com/user-attachments/assets/16505346-0b2e-4b90-95f2-7b1ff813024b)

**Comment by lexuanquynh** [comment] 2024-11-06 11:59
you can not scan all 7 images above. it will crash the app.

**Comment by axxel** [comment] 2024-11-06 16:06
I can decode those 7 images with `ZXingReader` from current HEAD just fine. Are you sure, this is the data that gets passed to `readCVPixelBuffer` in your app? I need the exact set of bytes that come from your camera that cause the crash in order to debug this.

Also setting your build environment to a release build is beyond the control of the `zxing-cpp` project.

**Comment by lexuanquynh** [comment] 2024-11-07 00:42
If you use the latest iOS, it scans QRCode normally.
If you use iOS 17.6.1, it will cause Crash.
I use your library as follows:
```bash
  pod 'zxing-cpp'
```

<img width="688" alt="Screenshot 2024-11-07 at 07 40 09" src="https://github.com/user-attachments/assets/24d0a8eb-4149-4e76-bd4a-28835b69b41e">

**Comment by axxel** [comment] 2024-11-07 07:16
I can't debug an iOS app. The failed assertion should not be depending on the environment but only on the `zxing-cpp` version used and the image data it is fed with. As I said: I need the data that your app is passing to `readCVPixelBuffer` when it crashes. You need to change your app to somehow store that data and then even better check yourself that `ZXingReader` runs into the same crash.

Maybe @parallaxe, @markusfisch or @benjohnde has some idea regarding the different iOS versions.

**Comment by markusfisch** [comment] 2024-11-07 09:29
I can read all of the QR Codes above on iOS 17.6.1 on an iPhone 11 Pro using the [Demo](https://github.com/zxing-cpp/zxing-cpp/tree/master/wrappers/ios/demo) project.

@lexuanquynh Can you please confirm that the unmodified Demo project does crash on your device?

**Comment by lexuanquynh** [comment] 2024-11-11 01:03
@markusfisch 
Can I send you a Testflight link?

**Comment by lexuanquynh** [comment] 2024-11-11 06:07
@markusfisch m

Here is your Demo project.
It still crashes with the above images.
<img width="1374" alt="Screenshot 2024-11-11 at 13 06 30" src="https://github.com/user-attachments/assets/db612b73-18e0-414c-9737-f24ba296389b">

**Comment by lexuanquynh** [comment] 2024-11-11 06:08
<img width="807" alt="Screenshot 2024-11-11 at 13 07 55" src="https://github.com/user-attachments/assets/98374570-9bbf-443d-9cd3-8757c87c990f">
[testflight_feedback.zip](https://github.com/user-attachments/files/17697395/testflight_feedback.zip)

**Comment by lexuanquynh** [comment] 2024-11-15 07:50
@markusfisch  Do you have an iPhone 11?
Did you see my comment above?

**Comment by markusfisch** [comment] 2024-11-15 08:45
@lexuanquynh Yes, I saw your comment, and sorry for the late response. I was trying to reproduce the crash with the demo project, but wasn't able to do it, unfortunately. I just have an iPhone 11 Pro at hand, but I really doubt that the crash is affecting just the iPhone 11 and not the Pro. 

I also checked the attached testflight feedback, thank you for that 👍  There, the "Hardware Model" mentioned in `crashlog.crash` is "iPhone12,1". So the crash happened on an iPhone 12, what makes me think that the crash is independent from specific hardware. Also I see you used the "Identifier" `com.zxing-cpp.ios.demo-codetoanbug`, which implies to me that this isn't the unmodified demo project.

Did you try the _unmodified_ demo project in Xcode, in debug mode, on your device? Without distributing a TestFlight app? And does exactly this code crash reading one of the above QR Codes? And if so, which QR Code exactly?

And yes, you can send me a TestFlight link, my Apple ID is "mf@markusfisch.de", but I wouldn't see the code and could only confirm that your app is crashing on my device too.

**Comment by lexuanquynh** [comment] 2024-11-15 08:54
@markusfisch 
Okay. I want to add you to my own forked project from your Demo project, and just change the identifier to push to my Apple develoment account. But I want to have a suggestion, that why can't we throw an error or return error instead of crashing the app with the asert command?

**Comment by axxel** [comment] 2024-11-15 09:18
> But I want to have a suggestion, that why can't we throw an error or return error instead of crashing the app with the asert command?

Because this assert only shows that somewhere else is a bug and I'd like to fix that bug, which in the best case leads to a successful detection.

**Comment by lexuanquynh** [comment] 2024-11-15 14:54
@markusfisch  @axxel 
If you have an Apple development account, please invite me to Testflight. I think it will be more objective if you build the application yourself from the Demo project. We will be the testers.
Or else I can setup you as admin of the app. You can push the build to my account with the build number. That way you can trust that the Demo Source code is unchanged except for the identifier to push the app.

**Comment by lexuanquynh** [comment] 2024-11-15 15:05
@axxel 
So send your apple id. I will setup admin rights for you. You will receive an email from Apple. Please accept.

**Comment by lexuanquynh** [comment] 2024-11-15 15:12
<img width="472" alt="Screenshot 2024-11-15 at 22 12 23" src="https://github.com/user-attachments/assets/c1e00ad1-caf6-4b7d-abea-27a2e2910ad3">

**Comment by lexuanquynh** [comment] 2024-11-15 15:21
@axxel 
Sorry for bothering you.
I'm just tinkering with Pods on my computer right now. So I'd really like the library to have some way to return errors instead of crashing the app with the assert function.

**Comment by markusfisch** [comment] 2024-11-16 10:18
Thanks for the invite! I'll accept it once I'm back to my computer.

But the TestFlight app will just show us that your app is crashing on my device too. I still wouldn't know **why**. Without your code, I simply can't tell why your app is crashing, and why the demo does work on my device with all the mentioned QR Codes.

So again, does the **unmodified** demo app work in Xcode on your device? 

1. Clone ZxingCpp 
2. Open wrapper/ios with Xcode
3. Connect your device 
4. Update signing for your account 
5. Press the play button 

Does this app crash with any of the above QR Codes? And if so, with which one?

I'm afraid I need an answer to this questions in order to be of any help.

**Comment by axxel** [comment] 2024-11-16 12:01
> So send your apple id. I will setup admin rights for you. You will receive an email from Apple. Please accept.

As it still seems unclear: I have no apple id, no apple account, no apple phones, no apple compiler, nothing. I can't help you unless you provide an image file that reproduces your crash with the `ZXingReader` example program that comes with the project.

**Comment by axxel** [comment] 2024-12-25 15:17
Without further feedback from the OP, I will close this issue.

**Comment by markusfisch** [comment] 2024-12-25 15:34
Just a little note: we recently found this in our crash logs, too. But as the last days of this year were quite busy, we postponed a closer inspection until next year.

It's happening very rarely. And I wasn't able to reproduce it so far.

**Closed** 2024-12-31 03:24 UTC
