### ISSUE TITLE
zxing.pc is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [zxing-cpp/zxing-cpp#335] opened 2022-05-09 04:33 UTC
As per title: `zxing.pc.in` has

```
prefix=@INSTALLDIR@
exec_prefix=${prefix}
libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```

and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to a broken .pc file on NixOS in particular.

Similar to open-source-parsers/jsoncpp#1199 and KhronosGroup/SPIRV-Tools#3905. See “[Concatenating paths when building pkg-config files][1]” for a discussion of the problem and a suggested fix (I don’t know CMake myself, sorry).

[1]: https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files

**Comment by axxel** [comment] 2022-05-09 09:44
Thanks a lot for the input. (Libreoffice uses this project?!? who would have thought... ;)).

Question: what version of cmake is generally available to your audience? 3.19 or newer by any chance? See jtojnar's comment here https://stackoverflow.com/questions/57382992/joining-paths-in-cmake. And also my question to him: https://github.com/jtojnar/cmake-snips/issues/7.

**Comment by axxel** [comment] 2022-05-09 10:32
I now discovered your patch
```
      --replace '$'{exec_prefix}/@CMAKE_INSTALL_LIBDIR@ @CMAKE_INSTALL_FULL_LIBDIR@ \
      --replace '$'{prefix}/@CMAKE_INSTALL_INCLUDEDIR@ @CMAKE_INSTALL_FULL_INCLUDEDIR@
```
But based your mentioned [Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files) doc, this solves one issue while possibly introducing another? (I don't understand the inner workings of the pkg-config workflow related to interpolations.) If I was sure your patch does not break other users/distros, I'd certainly apply it.

**Comment by alexshpilkin** [comment] 2022-05-09 10:38
@axxel Correct, that patch works for the purposes of Nixpkgs, where the user isn’t really supposed to move built software around and the paths passed to CMake are even guaranteed to be absolute, but for general usage you probably want that join_paths monster jsoncpp used. I don’t understand CMake well enough to advise you on it, unfortunately.

**Comment by a17r** [comment] 2022-07-14 09:01
join_paths is just awful. Use CMAKE_INSTALL_FULL_* variables if you need absolute paths, never mangle paths yourself using these vars. People 'moving software around' must fix their cmake/pkgconfig files themselves.

**Comment by axxel** [comment] 2022-07-14 09:23
@a17r so the patch I cited [here](https://github.com/nu-book/zxing-cpp/issues/335#issuecomment-1120928682) is the right way to move forward in your opinion or is it (as I understood it) fixing one use case while breaking another?

What made you come across this issue here?

**Comment by a17r** [comment] 2022-07-14 09:45
I came here because LibreOffice fails to build against 1.4.0 after cleaning up internal headers, and first thing I checked were known bugs about pkgconfig.

Well, "in my opinion", but the concept of moving software around is foreign to me. The patch cited will work for all distributions with their tooling in order, but checking the link above and reading how pkgconfig files are supposed to look, `cmake_path` seems to be the right solution. I am always vary of accumulating third-party modules, then never updating them, when there is a correct upstream path (heh) forward.

Again, being selfish, I'd simply raise cmake minimum version to 3.20, maybe check distribution support here: https://repology.org/project/cmake/versions

Otherwise, at least make a comment to drop the thirdparty module in the future (whenever raising cmake version) or make it conditional on the cmake version detected.

**Comment by axxel** [comment] 2022-07-14 13:38
So you agree that indeed neither the current code (note there is no `join_path` module involved a.t.m.) nor the patched one is the way to go but that this 'manual' path joining is indeed required to support both valid use cases? I still fail to see the use case of where the variable interpolation from a client side pkg-config call is required to make it work. So from my understanding the above patch would actually be a net win (in absence of a cmake 3.20 based solution).

As for your initial build break, I guess that was caused by f86c4b69ca40dd9cbbc556bdf092b8d7832bd036? Can you work with the `MultiFormatWriter` API? Note that has always been around so a switch inside LibreOffice would still make it compile with all earlier released versions. If I'm missing something here, please let me know before releasing 2.0 (see #333).

**Comment by axxel** [comment] 2023-01-01 17:25
@josch I'd be interested to know if you had some insight into this topic from your debian maintainer perspective? My currently preferred action would be to come up with some "if cmake >= 3.20 then use-new-cmake-path-command else use-code-as-is" logic for the 2.0 release.

**Comment by bjornfor** [comment] 2023-01-01 17:44
AFAIK, making things relocatable is somthing that *can* be valuable for cmake files, but not pkg-config files. I made a trivial fix for this issue here: https://github.com/zxing-cpp/zxing-cpp/pull/468

**Comment by josch** [comment] 2023-01-01 20:40
@axxel I think this is a NixOS specific issue and thus I guess that the NixOS people can give better input on what they need. As far as Debian is concerned, `CMAKE_INSTALL_{INCLUDE,LIB}DIR` will not be absolute during a normal package build and thus we do not see this issue in Debian. Also, we currently have cmake 3.25.1 in Debian unstable, so I wouldn't mind requring cmake >= 3.20. If you'd like me to try out a patch and see if it breaks anything for Debian, just point me to it. Thanks!

**Comment by axxel** [comment] 2023-01-01 20:47
Thanks @bjornfor and @josch for chiming in. I've just read the above mentioned info again, including the linked https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/, and came to the understanding that maintaining relative paths inside a pkg-config file is required if you want your client (dependent) project install their own data (like a module or a custom config-file) relative to your project root (e.g. a bash-completion file for your cli tool that aught to be installed relative to a potentially non-standard install path of bash). zxing-cpp does not have anything like this, so I believe using the suggested `CMAKE_INSTALL_FULL_<dir>` variables is fixing the NixOS issue while not introducing new problems. I'll merge #468 and revisit the subject as soon as someone complains again.

**Closed** 2023-01-01 20:47 UTC
