### ISSUE TITLE
BitArray.h: No such file or directory

### ISSUE THREAD

**Issue by Cerberios** [zxing-cpp/zxing-cpp#481] opened 2023-01-10 19:06 UTC
Hello there!
After release version media-libs/zxing-cpp-2.0.0 it is impossible to compile app-office/libreoffice because it falls with error:

[CXX] cui/source/options/connpoolconfig.cxx
/var/tmp/portage/app-office/libreoffice-7.5.0.1/work/libreoffice-7.5.0.1/cui/source/dialogs/QrCodeGenDialog.cxx:30:10: fatal error: BitArray.h: No such file or directory
   30 | #include <BitArray.h>
      |          ^~~~~~~~~~~~
compilation terminated.

Please, fix. Thanks!

**Comment by a17r** [comment] 2023-01-10 21:40
There is nothing to fix here, LibreOffice 7.5 branch is already fixed but not yet 7.5.0.1.

**Comment by axxel** [comment] 2023-01-11 00:01
Yes. This is a duplicate of #361. The mentioned libreoffice patch is [here](https://github.com/LibreOffice/core/commit/7f5a8384824b8570547ac982e07b6fb912af6e93).

**Comment by axxel** [comment] 2023-03-25 21:03
I did not check when exactly this was merged but the current release [7.5.2.2](https://git.libreoffice.org/core/+/refs/tags/libreoffice-7.5.2.2/cui/source/dialogs/QrCodeGenDialog.cxx) does contain the fix. -> closing.

**Closed by axxel** 2023-03-25 21:03 UTC
Labels: duplicate
