### ISSUE TITLE
Wrong Matrix on a different Pc

### ISSUE THREAD

**Issue by Abooow786** [zxing-cpp/zxing-cpp#693] opened 2023-12-21 13:17 UTC
Hey Community, Hey Axxel,

i got following Problem. I built a c++ Project and included the static library. Everything works perfect fine. Now i transferred my generated .exe to a different Pc. The Pc is old and still uses Windows 7. The Problem which i am facing is in the follwoing command:
" matrix = writer.encode(input, width, height);"

it is from the example ZXingWriter and im trying to generate a qr Code with following Input String"Hello World".
On the Windows 7 Pc i get a wrong Matrix back so the resulting QRCode is wrong. I debugged for hours to find out why.. Do you or somebody else know from where this Problen can come from?
Windows 7 QRCode:
![Windows7QrCode](https://github.com/zxing-cpp/zxing-cpp/assets/154526039/18c6de94-7754-484f-a776-b4f91d8b4c11)

Correct QRCode:
![QRCodecorrect](https://github.com/zxing-cpp/zxing-cpp/assets/154526039/e87e9f34-5036-47c8-ae57-30a4c18deb3c)

In the Matrix every 1 means black and 0 means white. So the change in the qrcodes are coming from a different generated matrix

Edit: I just tried it on another Windows 7 Computer and it works fine. So i'm guessing there is a wrong or old .dll or .lib file which zxing is may using which causes this behaviour. I cant reset the computer so anybody has a idea?

Thank youu

**Comment by axxel** [comment] 2023-12-21 15:05
That sounds very strange. I have no theory what the issue might be. I suggest you use a tool like [this](https://github.com/lucasg/Dependencies) to check which dlls are loaded at runtime for your exe and send me the list. Maybe I see something.

Also I'd be curious if the `ZXingWriter.exe` as is has the same problem on your machine.

Are you using a recent version of the library?

**Comment by Abooow786** [comment] 2023-12-21 22:04
Yeah im using the recent version.

Yes this behaviour also happens when i use the ZXingWriter.exe.
Could it be possible that the cpu is making Problems? Maybe it calculates something wrong(wrong rounding or cutting sth off)?

I will check the dlls tomorrow but i don‘t think that this is the problem. Then this behaviour would not happen in the ZXingWriter.exe. Is ZXing maybe using some dll at runtime?

**Comment by axxel** [comment] 2023-12-22 00:18
> Could it be possible that the cpu is making Problems?

A broken computer hardware (cpu, ram, whatever) can of course explain every bug imaginable but that sounds highly unlikely.

**Comment by Abooow786** [comment] 2023-12-22 07:00
Okay thanks. I will check the needed dlls later and will copy every needed dll from the working PC to the other one. I will give a feedback after i have some more details

**Comment by Abooow786** [comment] 2023-12-22 10:27
So i just used your suggested tool.
I selected the ZXingWriter.exe it uses follwing dll's:
![useddll (1)](https://github.com/zxing-cpp/zxing-cpp/assets/154526039/db4a1b4b-2c29-4bc7-b884-51c3a7243600)
Does it give you any idea?

**Comment by axxel** [comment] 2023-12-22 14:19
> Does it give you any idea?

No. As it is so unbelievable, let me make sure I understand your situation: You use this one executable and copy it to 2 different machines. You execute it on both with the same command line parameters. Let's say
```
ZXingWriter.exe qrcode Hello test.png
```
And you get two different results?

**Comment by Abooow786** [comment] 2023-12-22 14:51
Right. The above QRCode decodes „Hello World“
Like you can see they are like 90% identical. But unfortionaly not 100%..

**Comment by axxel** [comment] 2023-12-22 16:37
> The above QRCode decodes „Hello World“

No, it decodes to "Hello".

If you copy the 5 windows dlls into the folder next to your exe and open it again in the dependencies tool, you should see them picked up instead of the original ones from `Windows/System32`. If you then copy exe with the dlls to the other machine and you still get something different, then I'd consider this other machine to be 'broken'.

**Comment by axxel** [comment] 2024-01-03 21:34
If you don't have any new insights, I'll close this issue as "can't reproduce".

**Comment by Abooow786** [comment] 2024-01-06 17:14
Hey axxel, sorry for the late response.
I did not had the time to check the problem with copied dlls. I will try it on monday and will gill give you some feedback. So if anyone ever will have the same problem he may has a solution or does know there is no solution.

**Comment by axxel** [comment] 2024-01-18 19:43
Which Monday were you speaking of? ;-)

**Closed** 2024-01-24 01:17 UTC
