### ISSUE TITLE
Rectangular datamatrix

### ISSUE THREAD

**Issue by dariofinardi** [zxing-cpp/zxing-cpp#818] opened 2024-08-27 09:46 UTC
I found some weird not square datamatrix.

<img width="103" alt="Screenshot 2024-08-27 114505" src="https://github.com/user-attachments/assets/9da730b9-e9b0-4da4-ac33-f55a0982bf30">

Not Zxing, Zxing-CPP, ZBar are able to read them.
I tried with some other reader like the one from Cognex and it runs.

I just tried your webdemo and it works. 
I double checked my environment:
python 3.10
zxing-cpp==2.2.0

**Comment by dariofinardi** [comment] 2024-08-27 10:05
I just tried your webdemo and it works. I'll check if the prebuilt package on ubuntu is releasing the last version.

**Comment by dariofinardi** [comment] 2024-08-27 12:41
Found your README.
Ok, I'll proceed installing by hands.

**Comment by axxel** [comment] 2024-08-29 10:54
The zxing-cpp wheel version 2.2.0 published on PyPi seems to work just fine for your sample (on Linux). What is your issue?

**Comment by dariofinardi** [comment] 2024-08-29 11:15
The issue was about datamatrix decoding. The 2.2.0 from pypi seems not to be able to decode that format.
I built the native library by hands as you write in your readme and everything gone perfect.

**Comment by axxel** [comment] 2024-08-29 11:19
What platform/OS are you working on?

**Comment by dariofinardi** [comment] 2024-08-29 12:11
I'm on ubuntu 22.04 x64

**Comment by axxel** [comment] 2024-09-03 06:38
> I'm on ubuntu 22.04 x64

Then I'm pretty sure it should work, or let's say it is not an issue with the wheel itself. As I just tested it on my Ubuntu 24.04 x64. Even the 32bit version mentioned in the README would work for this particular image as the symbol is located right in the center of the image.

Anyway, since you found a solution and I can't reproduce the issue, I'm closing it.

**Closed by axxel** 2024-09-03 06:38 UTC
