### ISSUE TITLE
reading rotated DataMatrix barcodes without quiet zone

### ISSUE THREAD

**Issue by a3emdot** [zxing-cpp/zxing-cpp#590] opened 2023-07-17 09:54 UTC
(This is a followup issue to https://github.com/zxing-cpp/zxing-cpp/issues/589)

After the suggestion in Issue #589 I made a commit to my project
using ZXing::DecodeHints::setFormats(...).
The rotated QRCode barcodes can now be read but the DataMatrix barcodes still choke.

Hence I'm opening this issue, because the title of #589 was changed
by the project maintainer, and is thus not applicable anymore for this issue here.

Here is a link to my github project with the relevant commit.
https://github.com/a3emdot/zintzxingcppdemo/commit/cd15923b8475bca27b63ebf7037ffd8ec880e093

For building the project I used a Fedora installation with a properly setup developer installation.
It should be possible to run the reproducer simply by calling the bash script from the repo

cd zintzxingcppdemo
./ZintZXingCppDemo.sh

Observation: One can see a lot broken Tests in LastTest.log, all DataMatrix barcodes
Goal: A "clean" LastTest.log

I currently use the revisions
zint: https://github.com/zint/zint/commit/fae3e6d9d5263f71d5901453d7a8c0e2e1173209
zxing-cpp: https://github.com/zxing-cpp/zxing-cpp/commit/9a36d24e896b4f1f43544996e0f07f2434b4aa3b

- Andre

**Comment by a3emdot** [comment] 2023-07-17 09:56
[LastTest.log](https://github.com/zxing-cpp/zxing-cpp/files/12068020/LastTest.log)

**Comment by axxel** [comment] 2023-07-17 11:55
> The rotated QRCode barcodes can now be read but the DataMatrix barcodes still choke.

The first part of this statement surprises me, the second does not. See https://github.com/a3emdot/zintzxingcppdemo/blob/d37ff962a75e3272dcc016b9ea14a5b06ac58504/src/barcode.cpp#L551

I quote myself from #589: Neither setting isPure nor tryRotate should fix your issues.

**Comment by a3emdot** [comment] 2023-07-18 08:53
Only for the record, and to avoid potential misconceptions:

Issue #589 is reported against commit https://github.com/a3emdot/zintzxingcppdemo/commit/d1684b625c409e0e52e6b990420c5dc78f8ca5bd
(does NOT use ZXing::DecodeHints::setFormats(...))

Issue #590 is reported against commit https://github.com/a3emdot/zintzxingcppdemo/commit/cd15923b8475bca27b63ebf7037ffd8ec880e093
(does use ZXing::DecodeHints::setFormats(...))

Only these two commits contain testing with rotated barcodes,
both of these commits are on separate branches for bug reporting.
The main branch of my demo repo doesn't test with rotated barcodes yet.

**Comment by axxel** [comment] 2023-07-18 11:55
Thanks for the clarification, I did in fact miss something there. Please do the following: try to reproduce the issue by saving one of your problematic DM images to a file and run it through `ZXingReader`. Then please post that image here for me to inspect.

**Comment by axxel** [comment] 2023-07-18 14:26
That was informative. The problem is a yet undetected limitation of the DMDetector that is contradicting my earlier claim that it should "just work" as long as you don't specify `isPure`. It is related to #378. Bottom line: the symbol needs at least 1 pixel of quiet zone for the non-pure detection code to work. The fix for #378 was to simply try the `DetectPure` function as well but that does not work for rotated symbols.

To quickly fix this issue for you, I suggest you generate the symbols with a quiet zone as required by the specification.

**Comment by a3emdot** [comment] 2023-07-18 14:31
My workaround at the moment is to rotate by myself each barcode I would like to validate using 0, 90, 180 and 270
degrees. If one of the four variants can be read with the correct payload, i accept the barcode as readable for the moment.

**Comment by a3emdot** [comment] 2023-07-18 14:34
So the next question for me should be, if zint generated these barcodes with "incorrect" quiet zones?
Perhaps @gitlost might chime in?

**Comment by axxel** [comment] 2023-07-18 14:47
You should simply add the `BARCODE_QUIET_ZONES` flag to your `output_options`.

**Comment by gitlost** [comment] 2023-07-18 14:51
Hi, yes, for back-compatibility reasons zint only adds quiet zones if asked to (for most barcodes anyway).

**Comment by a3emdot** [comment] 2023-07-18 15:03
so for datamatrix barcodes one needs to explicitly activate quietzones for zint?

**Comment by gitlost** [comment] 2023-07-18 16:02
Yes, and for linear barcodes `COMPLIANT_HEIGHT` also.

**Comment by axxel** [comment] 2023-07-19 09:22
Generating symbols with quiet zones as required by the standard does not really sound like a "workaround" to me. If they were enabled by default in libzint, would you have disabled them?

**Comment by axxel** [comment] 2023-07-19 18:17
> of course NOT!

Then simply enable them as suggested and your problems go away. :)

What is your use case for detecting rotated barcodes without quiet zones?

**Comment by axxel** [comment] 2023-09-08 21:05
I was interested in getting to know your use case for detecting rotated datamatrix symbols without a quiet zone. This might have convinced me to put work into supporting that use case. Without this information, I'll close this issue soonish.

**Closed** 2023-09-14 09:25 UTC
